---
language: ruby

gemfile:
  - gemfiles/rails_4.gemfile
  - gemfiles/rails_5.gemfile
  - gemfiles/rails_6.gemfile
  - gemfiles/rails_master.gemfile

rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6

matrix:
  fast_finish: true
  exclude:
    - rvm: 2.3
      gemfile: gemfiles/rails_master.gemfile
    - rvm: 2.4
      gemfile: gemfiles/rails_master.gemfile
    - rvm: 2.3
      gemfile: gemfiles/rails_6.gemfile
    - rvm: 2.4
      gemfile: gemfiles/rails_6.gemfile

sudo: false

cache: bundler

install: bundle install --without development --retry=3 --jobs=3

script:
  - bundle exec rubocop
  - bundle exec rspec
